task:
  environment:
    TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
    TELEGRAM_CHAT: ${{ secrets.TELEGRAM_CHAT }}
    BRANCH: thirteen/main
    
  name: Build Kernel
  timeout_in: 2h
  container:
      image: panchajanya1999/archlinux:latest
      cpu: 8
      memory: 32G

  Build_script:
      - echo "LC_ALL=en_US.UTF-8" | sudo tee -a /etc/environment
      - echo "en_US.UTF-8 UTF-8" | sudo tee -a /etc/locale.gen
      - echo "LANG=en_US.UTF-8" | sudo tee -a /etc/locale.conf
      - sudo locale-gen en_US.UTF-8
      - wget https://raw.githubusercontent.com/Alessakrendly/my-script/main/build.sh
      - bash build.sh
