name: Building Kernel

on: 
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v3
    - name: Start Build
      env:
        TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
        TELEGRAM_CHAT: ${{ secrets.TELEGRAM_CHAT }}
        KBRANCH: ${{ secrets.KBRANCH }}
        GIT_TOKEN: ${{ secrets.GIT_TOKEN }}
        TC: ${{ secrets.TC }}
      run: |
        sudo apt update && sudo apt upgrade -y && sudo apt install python2 -y
        git clone --depth=1 -b $KBRANCH https://"$GIT_TOKEN":x-oauth-basic@github.com/XSans0/kernel_xiaomi_vayu kernel
        cd kernel
        wget https://raw.githubusercontent.com/XSans0/my-script/main/ci/build.sh
        bash build.sh
