name: Building Kernel

on: 
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Start Build
      env:
        BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
        CHID: ${{ secrets.CHID }}
        KBRANCH: ${{ secrets.KBRANCH }}
        GIT_TOKEN: ${{ secrets.GIT_TOKEN }}
        TC: ${{ secrets.TC }}
      run: |
        sudo apt update -y && sudo apt upgrade -y
        git clone --depth=1 -b $KBRANCH https://"$GIT_TOKEN":x-oauth-basic@github.com/XSans0/kernel_xiaomi_vayu kernel
        cd kernel
        wget https://raw.githubusercontent.com/XSans0/my-script/main/ci/build.sh
        bash build.sh
