name: Building NTR Kernel

on: 
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    container: 
      image: zycromerz/kerneldocker:v3

    steps:
    - uses: actions/checkout@v2
    - name: Compile NTR Kernel
      env:
        TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
        CHANNEL_ID: ${{ secrets.CHANNEL_ID }}
      run: |
        wget https://raw.githubusercontent.com/XSans02/CI_Script/main/vayu/startBuild
        bash startBuild stable clang14-llvm
